name: vis-tutorial
channels:
    - conda-forge
    - defaults
    - avishapiro
dependencies:
    - basemap=1.0.8.dev0
    - basemap-data-hires=1.0.8.dev0
    - bokeh=0.12.4
    - cartopy=0.15.1
    - holoviews=1.6.2
    - matplotlib=2.0.0
    - notebook=5.0.0
    - numpy=1.11.3
    - pandas=0.19.2
    - plotly=2.0.5
    - python=3.5.3
    - scipy=0.18.1
    - seaborn=0.7.1
    - statsmodels=0.8.0
    - xarray=0.9.1
    - cufflinks=0.8.2
    # - pyreadline=2.1
